import Head from "next/head";
import Welcome from "../components/Welcome";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Country statistics</title>
        <meta name="description" content="Generated by Samuel Mugisha" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Welcome />
      </main>

      <footer></footer>
    </div>
  );
}
